{
 "title": "MirrorMaker2 Lag Exporter Dashboard",
 "description": "This grafana dashboard provides the lag information of mirrormaker 2 process",
 "tags": [
  "strimzi",
  "mirrormaker"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic_Name",
    "query": {
     "query": "query_result(kafka_connect_mirror_lag)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Mirrormaker Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(kafka_connect_mirror_lag)" }
   ]
  },
  {
   "title": "Total Mirrormaker Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(kafka_connect_mirror_lag)", "legendFormat": "mirrormaker connector lag" }
   ]
  },
  {
   "title": "Topic wise lag ",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_connect_mirror_lag{topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_connect_mirror_lag{topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_mirror_lag{topic=~\"$topic\"}",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  }
 ]
}