# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'      # See 'Options' for more details
        distribution: 'graalvm' # See 'Supported distributions' for available options
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cache: maven
    - name: Test with JUnit
      run: mvn -B test --file pom.xml
    - name: Build with Maven
      run: mvn -B package -DskipTests -Dnative --file pom.xml
    - name: Verify build
      run: mvn -B test-compile failsafe:integration-test -Dnative
    - run: mkdir staging && cp target/*-runner staging/mm2-exporter
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
